@startuml overallflow

left to right direction

database GDC
component "GDC API" as gdc_api
file "RAW GDC\nJSON" as raw_gdc_json
component "GDC Value\nTransforms" as gdc_val_xform
file "GDC+\nJSON" as gdc_plus_json
component "GDC Structural\nTransforms" as gdc_s_xform
file "GDC in\nCCDH Model" as gdc_cda_model

GDC -> gdc_api 
gdc_api -> raw_gdc_json
raw_gdc_json -> gdc_val_xform 
gdc_val_xform -> gdc_plus_json
gdc_plus_json -> gdc_s_xform
gdc_s_xform -> gdc_cda_model


database PDC
component "PDC API" as pdc_api
file "RAW PDC\nJSON" as raw_pdc_json
component "PDC Value\nTransforms" as pdc_val_xform
file "PDC+\nJSON" as pdc_plus_json
component "PDC Structural\nTransforms" as pdc_s_xform
file "PDC in\nCCDH Model" as pdc_cda_model

PDC -> pdc_api 
pdc_api -> raw_pdc_json
raw_pdc_json -> pdc_val_xform 
pdc_val_xform -> pdc_plus_json
pdc_plus_json -> pdc_s_xform
pdc_s_xform -> pdc_cda_model

GDC --[hidden]> PDC
gdc_cda_model --[hidden]> pdc_cda_model

component Merge
gdc_cda_model -> Merge
pdc_cda_model -> Merge

file "Data in\nCCDH Model" as ccdh_model
Merge -> ccdh_model 

@enduml