# This is a basic workflow to help you get started with Actions

name: IDC Transform Integration Test

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Extract IDC data from IDC Data Commons repo 
        extract-idc idc_extract.jsonl.gz \
        --make_bq_table True \
        --dest_table_id gdc-bq-sample.idc_test.dicom_pivot_wave1_case \
        --case dg.4DFC/f178b884-99b4-4929-a5a5-bc226b27da50 \
        --make_bucket_file True
