name: Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: 'true'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics      
    - name: Unit tests
      run: |
        pip install pytest
        cd tests
        py.test
    - name: Integration tests
      run: |
        git lfs pull
        cd tests/integration
        extract-gdc gdc.jsonl.gz --cases gdc-case-list.txt  
        extract-pdc pdc.jsonl.gz pdc.files-per-sample-dict.json.gz --cases pdc-case-list.txt
        cda-transform gdc.jsonl.gz gdc.transf.jsonl.gz gdc-transform.yml
